# module file, use python syntax
# 'module name':( {'resource name 1': number, 'resource name 2': number ...}, power(mW), {'module name 1': number of interconnection wires, 'module name 2': number of interconnection wires, ...})

module_list = {
    'jpeg':   ({'LAB':4, 'RAM':1, 'DSP':1},3.5,{'sobel':8,'aes':9}),
    'fir':    ({'LAB':2, 'RAM':0, 'DSP':0},1,{'interp':10}),
    'sobel':  ({'LAB':2, 'RAM':1, 'DSP':0},1,{'interp':5,'jpeg':8}),
    'interp': ({'LAB':2, 'RAM':0, 'DSP':1},2,{'fir':10,'sobel':5}),
    'aes':    ({'LAB':4, 'RAM':0, 'DSP':0},2.5,{'jpeg':9})
}

